filebeat.inputs:
  # Verbindung herstellen und Topics mit benötigten Daten abonnieren  
  - type: mqtt
    enabled: true
    hosts: ["mqtt://10.0.0.21:1883"]
    topics:
      - "bpalab/ftfactory/i/bme680"
      - "bpalab/ftfactory/i/ldr"
    client_id: "filebeat_mqtt_client"
    keep_alive: "60s"
    qos: 1

    processors:
      # Hinzufügen der MQTT-Topic als separates Feld für die Filterung
      - add_fields:
          target: ""
          fields:
            topic: "%{[mqtt.topic]}"

      # Dekodierung der JSON-Struktur der MQTT-Nachrichten, damit separiert auf alle Felder der Nachricht zugegriffen werden kann
      - decode_json_fields:
          fields: ["message"]
          target: ""
          overwrite_keys: true

# Speichern von den MQTT-Nachrichten der definierten Topics in einen neuen Index in ElasticSearch
output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "ft-factory-sensor-data"

setup.template.enabled: false