filebeat.inputs:
  - type: mqtt
    enabled: true
    hosts: ["mqtt://10.0.0.21:1883"]
    topics:
      - "bpalab/ftfactory/i/bme680"
      - "bpalab/ftfactory/i/ldr"
    client_id: "filebeat_mqtt_client"
    keep_alive: "60s"
    qos: 1  # Quality of Service

    processors:
      - add_fields:
          target: ""
          fields:
            topic: "%{[mqtt.topic]}"  # Add topic as field in index
    
      - decode_json_fields:
          fields: ["message"]  # The Field that contains the JSON is unpacked
          target: ""  # Makes the unpacked fields appear in the top level of the structure
          overwrite_keys: true  # Overwrites existing fields with the same name, if available

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "ft-factory-sensor-data"

setup.template.enabled: false