services:
  mysql:
    image: mysql:9.2
    environment:
      - MYSQL_DATABASE=bpa_lab_demonstration_factory
      - MYSQL_ROOT_PASSWORD=P4ssword!
    ports:
      - 3070:3306
    healthcheck:
      test: ["CMD-SHELL", "mysql -h 127.0.0.1 -uroot -pP4ssword! -e 'SELECT 1' || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - ./sql/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    networks:
      - camunda-platform

  zeebe: # https://docs.camunda.io/docs/self-managed/platform-deployment/docker/#zeebe
    image: camunda/zeebe:${CAMUNDA_ZEEBE_VERSION}
    container_name: zeebe
    ports:
      - "26500:26500"
      - "9600:9600"
      - "8088:8080"
    environment: # https://docs.camunda.io/docs/self-managed/zeebe-deployment/configuration/environment-variables/
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_CLASSNAME=io.camunda.zeebe.exporter.ElasticsearchExporter
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_URL=http://elasticsearch:9200
      # default is 1000, see here: https://github.com/camunda/zeebe/blob/main/exporters/elasticsearch-exporter/src/main/java/io/camunda/zeebe/exporter/ElasticsearchExporterConfiguration.java#L259
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_BULK_SIZE=1
      # allow running with low disk space
      - ZEEBE_BROKER_DATA_DISKUSAGECOMMANDWATERMARK=0.998
      - ZEEBE_BROKER_DATA_DISKUSAGEREPLICATIONWATERMARK=0.999
      - CAMUNDA_DATABASE_URL=http://elasticsearch:9200
      - "JAVA_TOOL_OPTIONS=-Xms512m -Xmx512m"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "timeout 10s bash -c ':> /dev/tcp/127.0.0.1/9600' || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - zeebe:/usr/local/zeebe/data
    networks:
      - camunda-platform
    depends_on:
      - elasticsearch

  operate: # https://docs.camunda.io/docs/self-managed/platform-deployment/docker/#operate
    image: camunda/operate:${CAMUNDA_OPERATE_VERSION}
    container_name: operate
    ports:
      - "8081:8080"
    environment: # https://docs.camunda.io/docs/self-managed/operate-deployment/configuration/
      - CAMUNDA_OPERATE_ZEEBE_GATEWAYADDRESS=zeebe:26500
      - CAMUNDA_OPERATE_ELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_OPERATE_ZEEBEELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_OPERATE_CSRFPREVENTIONENABLED=false
      - CAMUNDA_DATABASE_URL=http://elasticsearch:9200
      - management.endpoints.web.exposure.include=health
      - management.endpoint.health.probes.enabled=true
    healthcheck:
      test: [ "CMD-SHELL", "wget -O - -q 'http://localhost:9600/actuator/health/readiness'" ]
      interval: 30s
      timeout: 1s
      retries: 5
      start_period: 30s
    networks:
      - camunda-platform
    depends_on:
      - zeebe
      - elasticsearch

  tasklist: # https://docs.camunda.io/docs/self-managed/platform-deployment/docker/#tasklist
    image: camunda/tasklist:${CAMUNDA_TASKLIST_VERSION}
    container_name: tasklist
    ports:
      - "8082:8080"
    environment: # https://docs.camunda.io/docs/self-managed/tasklist-deployment/configuration/
      - CAMUNDA_TASKLIST_ZEEBE_GATEWAYADDRESS=zeebe:26500
      - CAMUNDA_TASKLIST_ZEEBE_RESTADDRESS=http://zeebe:8080
      - CAMUNDA_TASKLIST_ELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_TASKLIST_ZEEBEELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_TASKLIST_CSRFPREVENTIONENABLED=false
      - CAMUNDA_DATABASE_URL=http://elasticsearch:9200
      - management.endpoints.web.exposure.include=health
      - management.endpoint.health.probes.enabled=true
    healthcheck:
      test: [ "CMD-SHELL", "wget -O - -q 'http://localhost:9600/actuator/health/readiness'" ]
      interval: 30s
      timeout: 1s
      retries: 5
      start_period: 30s
    networks:
      - camunda-platform
    depends_on:
      - zeebe
      - elasticsearch

  connectors: # https://docs.camunda.io/docs/components/integration-framework/connectors/out-of-the-box-connectors/available-connectors-overview/
    image: camunda/connectors-bundle:${CAMUNDA_CONNECTORS_VERSION}
    container_name: connectors
    ports:
      - "8085:8080"
    environment:
      - CAMUNDA_CLIENT_MODE=self-managed
      - CAMUNDA_CLIENT_ZEEBE_GRPCADDRESS=http://zeebe:26500
      - OPERATE_CLIENT_BASEURL=http://operate:8080
      - OPERATE_CLIENT_PROFILE=simple
      - management.endpoints.web.exposure.include=health
      - management.endpoint.health.probes.enabled=true
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/actuator/health/readiness" ]
      interval: 30s
      timeout: 1s
      retries: 5
      start_period: 30s
    env_file: connector-secrets.txt
    networks:
      - camunda-platform
    depends_on:
      - zeebe
      - operate

  elasticsearch: # https://hub.docker.com/_/elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      # allow running with low disk space
      - cluster.routing.allocation.disk.threshold_enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9200/_cat/health | grep -q green" ]
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - elastic:/usr/share/elasticsearch/data
    networks:
      - camunda-platform

  bpalabordermanagement:
    image: bpa_lab_demonstration_factory/ordermanagement
    environment:
      JDBC_DATABASE_URL: jdbc:mysql://mysql:3306/bpa_lab_demonstration_factory
      JAVA_TOOL_OPTIONS: -Dlogging.level.io.camunda.zeebe.client.impl.ZeebeCallCredentials=ERROR
      ZEEBE_GRPC_ADRESS: http://zeebe:26500
      ZEEBE_REST_ADRESS: http://zeebe:8080
    build:
      dockerfile: bpa_lab_ordermanagement.dockerfile
      no_cache: true
    depends_on:
      mysql:
        condition: service_healthy
      zeebe:
        condition: service_healthy

    networks:
      - camunda-platform

  bpalabproductioncontrol:
    image: bpa_lab_demonstration_factory/productioncontrol
    environment:
      JDBC_DATABASE_URL: jdbc:mysql://mysql:3306/bpa_lab_demonstration_factory
      JAVA_TOOL_OPTIONS: -Dlogging.level.io.camunda.zeebe.client.impl.ZeebeCallCredentials=ERROR
      ZEEBE_GRPC_ADRESS: http://zeebe:26500
      ZEEBE_REST_ADRESS: http://zeebe:8080
    build:
      dockerfile: bpa_lab_productioncontrol.dockerfile
      no_cache: true
    depends_on:
      mysql:
        condition: service_healthy
      zeebe:
        condition: service_healthy
    networks:
      - camunda-platform

  bpalabpurchasing:
    image: bpa_lab_demonstration_factory/purchasing
    environment:
      ZEEBE_ADDRESS: zeebe:26500
      CAMUNDA_AUTH_STRATEGY: NONE
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
    build:
      dockerfile: bpa_lab_purchasing.dockerfile
      no_cache: true
    depends_on:
      mysql:
        condition: service_healthy
      zeebe:
        condition: service_healthy
    networks:
      - camunda-platform

  bpalabmanufacturing:
    image: bpa_lab_demonstration_factory/manufacturing
    environment:
      JAVA_TOOL_OPTIONS: -Dlogging.level.io.camunda.zeebe.client.impl.ZeebeCallCredentials=ERROR
      ZEEBE_GRPC_ADRESS: http://zeebe:26500
      ZEEBE_REST_ADRESS: http://zeebe:8080
    build:
      dockerfile: bpa_lab_manufacturing.dockerfile
      no_cache: true
    depends_on:
      zeebe:
        condition: service_healthy
    networks:
      - camunda-platform

  bpalabwarehouse:
    image: bpa_lab_demonstration_factory/warehouse
    environment:
      JAVA_TOOL_OPTIONS: -Dlogging.level.io.camunda.zeebe.client.impl.ZeebeCallCredentials=ERROR
      ZEEBE_GRPC_ADRESS: http://zeebe:26500
      ZEEBE_REST_ADRESS: http://zeebe:8080
#      MQTTBROKER_ADRESS: ws://host.docker.internal:9001
    build:
      dockerfile: bpa_lab_warehouse.dockerfile
      no_cache: true
    depends_on:
      zeebe:
        condition: service_healthy
    networks:
      - camunda-platform

  bpalabshipment:
    image: bpa_lab_demonstration_factory/shipment
    environment:
      ZEEBE_ADDRESS: zeebe:26500
      CAMUNDA_AUTH_STRATEGY: NONE
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
    build:
      dockerfile: bpa_lab_shipment.dockerfile
      no_cache: true
    depends_on:
      mysql:
        condition: service_healthy
      zeebe:
        condition: service_healthy
    networks:
      - camunda-platform

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - camunda-platform

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3008:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana_dashboards:/var/lib/grafana/dashboards
      - ./provision:/etc/grafana/provisioning
    depends_on:
      - elasticsearch
    networks:
      - camunda-platform

  # Filebeat to ingest data from MQTT-Broker to ElasticSearch 
  # ONLY POSSIBLE  IF THERE IS A CONNECTION TO THE MQTT_BROKER (RASPBERRY PI) AND FT_FACTORY OF THE BPA-LAB!
  filebeat:
    build:
      context: ./filebeat
      dockerfile: Dockerfile.filebeat
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    networks:
      - camunda-platform
    depends_on:
      - elasticsearch

  trino:
    image: trinodb/trino:435
    container_name: trino
    ports:
      - "8089:8080"
    volumes:
      - ./trino-config:/etc/trino/catalog
    networks:
      - camunda-platform

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8086:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=P4ssword!
    depends_on:
      - mysql
    networks:
      - camunda-platform

volumes:
  zeebe:
  elastic:
  grafana_data:
  mysql_data:

networks:
  camunda-platform:
