services:
  # ------------- BPALab Dataarchitecture
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3008:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana_dashboards:/var/lib/grafana/dashboards
      - ./provision:/etc/grafana/provisioning
    depends_on:
      - trino
    networks:
      - secondary-storage

  trino:
    image: trinodb/trino
    container_name: trino
    ports:
      - "8089:8080"
    volumes:
      - ./trino-config:/etc/trino/catalog
    depends_on:
      - mysql-secondary
    networks:
      - secondary-storage


volumes:
  grafana_data:
    name: grafana_data
