services:
  # ------------- BPALab Dataarchitecture
  bpalabmqtt2mongodb:
    image: bpa_lab_demonstration_factory/mqtt_2_mongodb
    environment:
      MONGODB_URI: mongodb://host.docker.internal:27017
      MQTT_BROKER_URL: ws://10.0.0.12:9001
    build:
      dockerfile: bpa_lab_mqtt_2_mongodb.dockerfile
      no_cache: true
    depends_on:
      - mongodb
    networks:
      - secondary-storage

  mongodb:
    image: mongo:8.0.4
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
    networks:
      - secondary-storage

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3008:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana_dashboards:/var/lib/grafana/dashboards
      - ./provision:/etc/grafana/provisioning
    depends_on:
      - trino
    networks:
      - secondary-storage

  trino:
    image: trinodb/trino
    container_name: trino
    ports:
      - "8089:8080"
    volumes:
      - ./trino-config:/etc/trino/catalog
    depends_on:
      - mysql-secondary
    networks:
      - secondary-storage


volumes:
  grafana_data:
    name: grafana_data
  mongodbdata:
