# use docker-compose.yml for camunda and mysql
# use docker-processes.yml for BpaLab process container
# use docker-dataarch.yml for kibana, trino, grafana
include:
  - docker-compose.yml
  - docker-processes.yml
  - docker-dataarch.yml
