services:
  # ------------- BPALab Dataarchitecture
  kibana:
    image: docker.elastic.co/kibana/kibana:9.4.4
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - camunda

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3008:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana_dashboards:/var/lib/grafana/dashboards
      - ./provision:/etc/grafana/provisioning
    depends_on:
      - trino
    networks:
      - camunda

  # Filebeat to ingest data from MQTT-Broker to ElasticSearch
  # ONLY POSSIBLE  IF THERE IS A CONNECTION TO THE MQTT_BROKER (RASPBERRY PI) AND FT_FACTORY OF THE BPA-LAB!
  filebeat:
    build:
      context: ./filebeat
      dockerfile: Dockerfile.filebeat
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    networks:
      - camunda
    depends_on:
      - elasticsearch

  trino:
    image: trinodb/trino
    container_name: trino
    ports:
      - "8089:8080"
    volumes:
      - ./trino-config:/etc/trino/catalog
    depends_on:
      - elasticsearch
      #condition: service_healthy
      - mysql
    networks:
      - camunda


volumes:
  grafana_data:

networks:
  camunda:
    name: camunda
