
services:
  # ---------------- BPALab container -----------------
  #  Process Container

  bpalabordermanagement:
    image: bpa_lab_demonstration_factory/ordermanagement
    environment:
      JDBC_DATABASE_URL: jdbc:mysql://mysql-secondary:3306/bpa_lab_demonstration_factory
      JAVA_TOOL_OPTIONS: -Dlogging.level.io.camunda.zeebe.client.impl.ZeebeCallCredentials=ERROR
      ZEEBE_REST_ADRESS: http://orchestration:8080
    build:
      dockerfile: bpa_lab_ordermanagement.dockerfile
      no_cache: true
    depends_on:
      mysql-secondary:
        condition: service_healthy
      orchestration:
        # Wait for orchestration service to be healthy, otherwise we get a lot of noisy logs from connection errors
        condition: service_healthy

    networks:
      - camunda
      - secondary-storage

  bpalabproductioncontrol:
    image: bpa_lab_demonstration_factory/productioncontrol
    environment:
      JDBC_DATABASE_URL: jdbc:mysql://mysql-secondary:3306/bpa_lab_demonstration_factory
      JAVA_TOOL_OPTIONS: -Dlogging.level.io.camunda.zeebe.client.impl.ZeebeCallCredentials=ERROR
      ZEEBE_GRPC_ADRESS: http://orchestration:26500
      ZEEBE_REST_ADRESS: http://orchestration:8080
    build:
      dockerfile: bpa_lab_productioncontrol.dockerfile
      no_cache: true
    depends_on:
      mysql-secondary:
        condition: service_healthy
      orchestration:
        # Wait for orchestration service to be healthy, otherwise we get a lot of noisy logs from connection errors
        condition: service_healthy
    networks:
      - camunda
      - secondary-storage

  bpalabmanufacturing:
    image: bpa_lab_demonstration_factory/manufacturing
    environment:
      JAVA_TOOL_OPTIONS: -Dlogging.level.io.camunda.zeebe.client.impl.ZeebeCallCredentials=ERROR
      ZEEBE_GRPC_ADRESS: http://orchestration:26500
      ZEEBE_REST_ADRESS: http://orchestration:8080
    #      MQTTBROKER_ADRESS: ws://host.docker.internal:9001
    build:
      dockerfile: bpa_lab_manufacturing.dockerfile
      no_cache: true
    depends_on:
      orchestration:
        # Wait for orchestration service to be healthy, otherwise we get a lot of noisy logs from connection errors
        condition: service_healthy
    networks:
      - camunda

  bpalabwarehouse:
    image: bpa_lab_demonstration_factory/warehouse
    environment:
      JAVA_TOOL_OPTIONS: -Dlogging.level.io.camunda.zeebe.client.impl.ZeebeCallCredentials=ERROR
      ZEEBE_GRPC_ADRESS: http://orchestration:26500
      ZEEBE_REST_ADRESS: http://orchestration:8080
    #      MQTTBROKER_ADRESS: ws://host.docker.internal:9001
    build:
      dockerfile: bpa_lab_warehouse.dockerfile
      no_cache: true
    depends_on:
      orchestration:
        # Wait for orchestration service to be healthy, otherwise we get a lot of noisy logs from connection errors
        condition: service_healthy
    networks:
      - camunda

  bpalabpurchasing:
    image: bpa_lab_demonstration_factory/purchasing
    environment:
      ZEEBE_ADDRESS: orchestration:26500
      CAMUNDA_AUTH_STRATEGY: NONE
      MYSQL_HOST: mysql-secondary
      MYSQL_PORT: 3306
    build:
      dockerfile: bpa_lab_purchasing.dockerfile
      no_cache: true
    depends_on:
      mysql-secondary:
        condition: service_healthy
      orchestration:
        # Wait for orchestration service to be healthy, otherwise we get a lot of noisy logs from connection errors
        condition: service_healthy
    networks:
      - camunda
      - secondary-storage

  bpalabshipment:
    image: bpa_lab_demonstration_factory/shipment
    environment:
      ZEEBE_ADDRESS: orchestration:26500
      CAMUNDA_AUTH_STRATEGY: NONE
      MYSQL_HOST: mysql-secondary
      MYSQL_PORT: 3306
    build:
      dockerfile: bpa_lab_shipment.dockerfile
      no_cache: true
    depends_on:
      mysql-secondary:
        condition: service_healthy
      orchestration:
        # Wait for orchestration service to be healthy, otherwise we get a lot of noisy logs from connection errors
        condition: service_healthy
    networks:
      - camunda
      - secondary-storage
