connector.name=mysql
connection-url=jdbc:mysql://mysql-secondary:3306
connection-user=root
connection-password=rootcamunda
case-insensitive-name-matching=true
insert.non-transactional-insert.enabled=true