camunda:
  client:
    mode: self-managed
    zeebe:
      enabled: true

# MQTT Client Configuration
ftfactorymqttclient:
  #broker: ws://host.docker.internal:9001
  broker: ws://localhost:9001
  clientId: FTFactoryMQTTClient

  # MQTT Topics Configuration
  cloudTopicPrefix: bpalab/ftfactory
  cloudPubOrderTopic: bpalab/ftfactory/f/o/order
  cloudBroadcastTopic: bpalab/ftfactory/o/broadcast
  cloudSubOrderTopic: bpalab/ftfactory/f/i/order
  cloudHBWTopic: bpalab/ftfactory/f/i/stock
  cloudBME680Topic: bpalab/ftfactory/i/bme680