# camunda8.8 full
#    auth:
#      client-id: orchestration
#      client-secret: secret
camunda:
  client:
    mode: self-managed
    zeebe:
      enabled: true
      rest-address: ${ZEEBE_REST_ADRESS:http://localhost:8088}
      grpc-address: ${ZEEBE_GRPC_ADRESS:http://localhost:26500}

# MQTT Client Configuration
# FtFactory Cloud Broker
#spring:
#  config:
#    activate:
#      on-profile: factory
ftwarehousemqttclient:
  broker: ${MQTTBROKER_ADRESS:ws://localhost:9001}
  clientId: FTWarehouseMQTTClient
  # MQTT Topics Configuration
  fetchTopic: bpalab/ftwarehouse/fetch
  getTopic: bpalab/ftwarehouse/get
  noBikeTopic: bpalab/ftwarehouse/nobike
  putTopic: bpalab/ftwarehouse/put
  noPlaceTopic: bpalab/ftwarehouse/noplace
  storageTopic: bpalab/ftwarehouse/storage
  infoTopic: bpalab/ftwarehouse/info
  fetchedBikeTopic: bpalab/ftwarehouse/fetchedBike
  storedPlaceTopic: bpalab/ftwarehouse/storedPlace
# important dashes
---
# important

# local Broker not on 8081 because of camunda operate !
#spring:
#  config:
#    activate:
#      on-profile: local
#ftfactorymqttclient:
  #broker: ws://host.docker.internal:9001
#  broker: ws://localhost:9001
#  clientId: FTFactoryMQTTClient

  # MQTT Topics Configuration
#  cloudTopicPrefix: bpalab/ftfactory
#  cloudPubOrderTopic: bpalab/ftfactory/f/o/order
#  cloudBroadcastTopic: bpalab/ftfactory/o/broadcast
#  cloudSubOrderTopic: bpalab/ftfactory/f/i/order
#  cloudHBWTopic: bpalab/ftfactory/f/i/stock
#  cloudBME680Topic: bpalab/ftfactory/i/bme680

